# Logistic Regreesion

In [140]:
import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split

In [141]:
df = pd.read_csv("covid_toy.csv")
df.head(3)

age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No
1   27   Male  100.0  Mild    Delhi       Yes
2   42   Male  101.0  Mild    Delhi        No

In [142]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [143]:
si = SimpleImputer()
df['fever'] = si.fit_transform(df[['fever']])
df.isnull().sum()

age          0
gender       0
fever        0
cough        0
city         0
has_covid    0
dtype: int64

In [144]:
from sklearn.preprocessing import LabelEncoder

In [145]:
lb = LabelEncoder()
df['gender'] = lb.fit_transform(df['gender'])
df['cough'] = lb.fit_transform(df['cough'])
df['city'] = lb.fit_transform(df['city'])
df['has_covid'] = lb.fit_transform(df['has_covid'])

In [146]:
x = df.drop(columns= ['has_covid'])
y = df['has_covid']

In [147]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state=42)

In [148]:
from sklearn.linear_model import LogisticRegression

In [149]:
lr = LogisticRegression()
lr.fit(x_train,y_train)
y_pred = lr.predict(x_test)

In [150]:
from sklearn.metrics import accuracy_score, confusion_matrix
accuracy = accuracy_score(y_test,y_pred)
print(f"Accuracy score: {accuracy*100:.2f}%")

confusion = confusion_matrix(y_test,y_pred)
print(f"Confusion Matrix:")
print(confusion)

Accuracy score: 75.00%
Confusion Matrix:
[[9 4]
 [1 6]]


# USerBehavior

In [152]:
df = pd.read_csv("userbehaviour.csv")
df

userid  Average Screen Time  Average Spent on App (INR)  Left Review  \
0      1001                 17.0                       634.0            1   
1      1002                  0.0                        54.0            0   
2      1003                 37.0                       207.0            0   
3      1004                 32.0                       445.0            1   
4      1005                 45.0                       427.0            1   
..      ...                  ...                         ...          ...   
994    1995                 38.0                       938.0            0   
995    1996                 43.0                        61.0            0   
996    1997                 47.0                       761.0            0   
997    1998                  6.0                        73.0            1   
998    1999                  9.0                        54.0            0   

     Ratings  New Password Request  Last Visited Minutes       Status  
0          9                     7                  2990    Installed  
1          4                     8                 24008  Uninstalled  
2          8                     5                   971    Installed  
3          6                     2                   799    Installed  
4          5                     6                  3668    Installed  
..       ...                   ...                   ...          ...  
994        5                     4                  1865    Installed  
995        6                     8                  1327    Installed  
996        6                     1                  1936    Installed  
997        5                     1                  3436    Installed  
998        4                     2                  4039    Installed  

[999 rows x 8 columns]

In [153]:
df.isnull().sum()

userid                        0
Average Screen Time           0
Average Spent on App (INR)    0
Left Review                   0
Ratings                       0
New Password Request          0
Last Visited Minutes          0
Status                        0
dtype: int64

In [154]:
lb = LabelEncoder()
df['Status'] = lb.fit_transform(df['Status'])

In [155]:
df['Status'].value_counts()

Status
0    916
1     83
Name: count, dtype: int64

In [156]:
x = df.drop(columns= ['Status'])
y = df['Status']

In [157]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state=42)

In [194]:
lr = LogisticRegression(max_iter=100)
lr.fit(x_train,y_train)
y_pred = lr.predict(x_test)

In [196]:
from sklearn.metrics import accuracy_score, confusion_matrix
accuracy = accuracy_score(y_test,y_pred)
print(f"Accuracy score: {accuracy*100:.2f}%")

confusion = confusion_matrix(y_test,y_pred)
print(f"Confusion Matrix:")
print(confusion)

Accuracy score: 54.00%
Confusion Matrix:
[[58 49]
 [43 50]]


# Placement Dataset

In [160]:
df = pd.read_csv("newplacementdata.csv")
df

cgpa  placement_exam_marks  placed
0    7.19                    26       1
1    7.46                    38       1
2    7.54                    40       1
3    6.42                     8       1
4    7.23                    17       0
..    ...                   ...     ...
995  8.87                    44       1
996  9.12                    65       1
997  4.89                    34       0
998  8.62                    46       1
999  4.90                    10       1

[1000 rows x 3 columns]

In [161]:
x = df.drop(columns = ['placed'])

In [162]:
y = df['placed']

In [163]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state=42)

In [164]:
lr = LogisticRegression()
lr.fit(x_train,y_train)
y_pred = lr.predict(x_test)

In [165]:
from sklearn.metrics import accuracy_score, confusion_matrix
accuracy = accuracy_score(y_test,y_pred)
print(f"Accuracy score: {accuracy*100:.2f}%")

confusion = confusion_matrix(y_test,y_pred)
print(f"Confusion Matrix:")
print(confusion)

Accuracy score: 54.00%
Confusion Matrix:
[[58 49]
 [43 50]]
